### ISSUE TITLE
Trouble installing along side existing modes

### ISSUE THREAD

**Issue by dcwalker** [zenangst/Coda-2-Modes#8]
I already had a custom mode installed when I tried to install this bundle of modes.  I couldn't follow the instructions in the readme and ended up checking the git repo out to another location and symlinking to it in the modes directory.  It would be nice to be able to checkout a specific mode (in my case Ruby.mode) into my modes directory (ala Markdown.mode -- https://github.com/bobthecow/Markdown.mode).

**Comment by zenangst** [comment]
Good point sir, I'm gonna look into splitting them up into separate repositories.

**Comment by zenangst** [comment]
Fixed in https://github.com/zenangst/Coda-2-Modes/commit/ae9208eb096e86ed138576a79574b4685949c2dc

Now the mode is located here: https://github.com/zenangst/Ruby.mode

**Comment by dcwalker** [comment]
Fantastic! Thank you.
